services:
  backend:
    build:
      context: ./observer_backend
    container_name: prod_observer_backend
    ports:
      - "8000:8000"
    env_file:
      - ./env/prod.env # Default is production
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - observer_network
    command: sh -c "/wait-for-it.sh mariadb:3306 -- python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: ./observer_frontend
    container_name: prod_observer_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - observer_network
    command: sh -c "npm install && npm start"

  mariadb:
    image: mariadb:latest
    container_name: prod_observer_mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: prod_observer_dashboard_database
      MYSQL_USER: observer
      MYSQL_PASSWORD: observer123
    volumes:
      - prod_mariadb_data:/var/lib/mysql
    networks:
      - observer_network
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  prod_mariadb_data:


networks:
  observer_network:
