services:
  backend:
    build:
      context: ./observer_backend
    container_name: observer_backend
    ports:
      - "8000:8000"
    depends_on:
      - mariadb
      - neo4j
    networks:
      - observer_network

  frontend:
    build:
      context: ./observer_frontend
    container_name: observer_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - observer_network

  mariadb:
    image: mariadb:latest
    container_name: observer_mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: observer_dashboard_database
      MYSQL_USER: observer
      MYSQL_PASSWORD: observer123
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - observer_network

  neo4j:
    image: neo4j:latest
    container_name: observer_neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/observer
    volumes:
      - neo4j_data:/data
    networks:
      - observer_network

volumes:
  mariadb_data:
  neo4j_data:


networks:
  observer_network:
