services:
  backend:
    container_name: prod_observer_backend
    env_file:
      - ./env/prod.env
    restart: unless-stopped

  frontend:
    container_name: prod_observer_frontend
    env_file:
      - ./env/prod.env
    restart: unless-stopped

  mariadb:
    container_name: prod_observer_mariadb
    restart: unless-stopped
